name: New Release of Latex Document
on:
  push:
    branches:
      - 'main'

jobs:
  release_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: article/
          continue_on_error: true
      - name: Rename file
        id: date
        env:
          NOW: $(date +'%Y-%m-%d')
        run: mv article/main.pdf article/artigo_versao_${{ env.NOW }}.pdf
      - name: Create Release     
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Artigo Versao  ${{ env.NOW }}"
          files: |
            article/artigo_versao_${{ env.NOW }}.pdf
