name: Build LaTeX document
on: pull_request

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: article/
          continue_on_error: true
      - name: Save PDF as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: article/main.pdf
      - name: Display structure of downloaded files
        run: ls -R
      - name: comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const jq = require('jq-web');

            const getArtifactUrl = async () => {
              const response = await axios.get(`https://api.github.com/repos/${context.repo.owner}/${context.repo.repo}/actions/artifacts?per_page=100`, {
                headers: {
                  'Authorization': `token ${process.env.GITHUB_TOKEN}`,
                  'Accept': 'application/vnd.github.v3+json'
                }
              });

              const artifacts = jq.json(response.data, '[.artifacts[] | {name : .name, archive_download_url : .archive_download_url}]');
              const artifact = artifacts.find(artifact => artifact.name === 'main');
              return artifact ? artifact.archive_download_url : '';
            }

            const artifactUrl = await getArtifactUrl();
            const currentDate = new Date().toLocaleString("pt-BR", {timeZone: "America/Sao_Paulo"});
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Aqui está uma nova versão do artigo em PDF: [link](${artifactUrl}). Lançado em ${currentDate}.`
            })